// Copyright (c) 2019-present, Personal. All Rights Reserved.
const flatListData = [
    {
        key: 'a001',
        name: 'Đậu',
        sdt: '0123456789',
        status: 'miss_call',
        time: '2:37 PM',
        ct: 'Work',
        ava: 'https://facebook.github.io/react-native/img/tiny_logo.png',
    },
    {
        key: 'a002',
        name: 'Join Switch',
        sdt: '0123456789',
        status: 'miss_call',
        time: '4:37 AM',
        ct: 'Work',
        ava: 'https://facebook.github.io/react-native/img/tiny_logo.png',
    },

    {
        key: 'a003',
        name: 'Boss VRS',
        sdt: '0123456789',
        status: 'miss_call',
        time: '4:37 PM',
        ct: 'Work',
        ava: 'https://facebook.github.io/react-native/img/tiny_logo.png',
    },
    {
        key: 'a004',
        name: 'M Luffi',
        sdt: '0123456789',
        status: 'called',
        time: '5:37 PM',
        ct: 'Work',
        ava: 'https://facebook.github.io/react-native/img/tiny_logo.png',
    },
    {
        key: 'a005',
        name: 'D. Roger',
        sdt: '0123456789',
        status: 'miss_call',
        time: '6:37 PM',
        ct: 'Work',
        ava: 'https://facebook.github.io/react-native/img/tiny_logo.png',
    },
    {
        key: 'a006',
        name: 'Shara Han',
        sdt: '0123456789',
        status: 'miss_call',
        time: '7:37 PM',
        ct: 'School',
        ava: 'https://facebook.github.io/react-native/img/tiny_logo.png',
    },
    {
        key: 'a007',
        name: 'Maria Anabell',
        sdt: '0912345055',
        status: 'miss_call',
        time: '8:30 PM',
        ct: 'Work',
        ava: 'https://facebook.github.io/react-native/img/tiny_logo.png',
    },
    {
        key: 'a008',
        name: 'Jion Snow',
        sdt: '0912345055',
        status: 'called',
        time: '9:37 PM',
        ct: 'Home',
        ava: 'https://facebook.github.io/react-native/img/tiny_logo.png',
    },
    {
        key: 'a009',
        name: 'Jion Snow',
        sdt: '0912345055',
        status: 'called',
        time: '9:37 PM',
        ct: 'Home',
        ava: 'https://facebook.github.io/react-native/img/tiny_logo.png',
    },
    {
        key: 'a0010',
        name: 'Jion Snow',
        sdt: '0912345055',
        status: 'called',
        time: '9:37 PM',
        ct: 'Home',
        ava: 'https://facebook.github.io/react-native/img/tiny_logo.png',
    },
]

export default flatListData
